### ISSUE TITLE
no binary in releases

### ISSUE THREAD

**Issue by seamusabshere** [BurntSushi/rust-snappy#27]
hi,

https://faraday.io/ loves `szip`. We use it a lot, having installed it from `cargo install szip`.

It would be nice if you had a downloadable binary in https://github.com/BurntSushi/rust-snappy/releases!

thanks,
Seamus and the Faraday team

**Comment by BurntSushi** [comment]
Normally I wouldn't this for such a small binary because of the added maintenance burden, but I wanted to figure out how releases and GitHub Actions worked before moving more complex projects to them. So I decided to use szip as my guinea pig.

So, here's szip 1.0.0: https://github.com/BurntSushi/rust-snappy/releases/tag/szip-1.0.0

Do note that I stripped down the dependencies of `szip` quite a bit, so if you wanted to do a `cargo install szip`, it should be quicker than before.
